server:
  port: 8099

spring:
  application:
    name: TRANSACTION-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/bankDB?createDatabaseIfNotExist=true
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost