server:
  port: 8099

spring:
  application:
    name: TRANSACTION-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb?createDatabaseIfNotExist=true
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs

token:
  secret: 6D7662M7gmjq6qo736C35616B70sI5zyWiPKmrOsJuctP766B37396F746A71647F